apiVersion: v1
kind: Secret
metadata:
  name: ziv-secret
  annotations:
    avp.kubernetes.io/path: "application/data/bindid/aws/development/eu-west-1/global"
type: Opaque
stringData:
  apple-creds-id: <APPLE_CLIENT_ID>
